[2022-06-07 04:11:44,888] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: hero_info.hero_external_table_task scheduled__2022-06-06T04:00:00+00:00 [queued]>
[2022-06-07 04:11:44,946] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: hero_info.hero_external_table_task scheduled__2022-06-06T04:00:00+00:00 [queued]>
[2022-06-07 04:11:44,946] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 04:11:44,946] {taskinstance.py:1358} INFO - Starting attempt 1 of 2
[2022-06-07 04:11:44,946] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 04:11:44,957] {taskinstance.py:1378} INFO - Executing <Task(BigQueryCreateExternalTableOperator): hero_external_table_task> on 2022-06-06 04:00:00+00:00
[2022-06-07 04:11:44,965] {standard_task_runner.py:52} INFO - Started process 64402 to run task
[2022-06-07 04:11:44,970] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hero_info', 'hero_external_table_task', 'scheduled__2022-06-06T04:00:00+00:00', '--job-id', '15808', '--raw', '--subdir', 'DAGS_FOLDER/ingest_heroes.py', '--cfg-path', '/tmp/tmpihllv978', '--error-file', '/tmp/tmpfd7pltfx']
[2022-06-07 04:11:44,971] {standard_task_runner.py:80} INFO - Job 15808: Subtask hero_external_table_task
[2022-06-07 04:11:45,029] {task_command.py:370} INFO - Running <TaskInstance: hero_info.hero_external_table_task scheduled__2022-06-06T04:00:00+00:00 [running]> on host 76384e2d8475
[2022-06-07 04:11:45,188] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hero_info
AIRFLOW_CTX_TASK_ID=hero_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T04:00:00+00:00
[2022-06-07 04:11:45,191] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-06-07 04:11:45,191] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-06-07 04:11:45,599] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=hero_info, task_id=hero_external_table_task, execution_date=20220606T040000, start_date=20220607T041144, end_date=20220607T041145
[2022-06-07 04:11:45,624] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-07 04:11:45,679] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
